# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c476cbe90f37426e90ce1731208f2707b8ebbb39ca75dd8709308e1d9f5b4b2745011916de2a24e7fd804de773323cc5efad2ce7ab53574e76fb49ce93be155f

test:
  secret_key_base: 1ef3be1d403525f27e437efc91bc2ca124aa3263e14639752b300eb1f3d56e5966b0b473c254b2de091da6405739e6974a0315066f79f75702c5541d4f1dcd37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
